name: lint_python
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
      - run: pip install black codespell flake8
      - run: black --check . || true
      - run: codespell --quiet-level=2  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: pip install requests
      - run: pip install -r requirements.txt || true
      - run: python test_program.py
      - run: python test_program_json.py
      - run: python test_program_timing.py
